// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bca-vibes/CoolPrecision.tsx": () => import("../components/mockups/bca-vibes/CoolPrecision.tsx"),
  "./components/mockups/bca-vibes/SoftAuthority.tsx": () => import("../components/mockups/bca-vibes/SoftAuthority.tsx"),
  "./components/mockups/bca-vibes/WarmExecutive.tsx": () => import("../components/mockups/bca-vibes/WarmExecutive.tsx")
};
