export const cmsContent: { key: string; value: string }[] = [
  { key: "hero.headline", value: "Automation Without the Operational Burden" },
  { key: "hero.subheadline", value: "We deliver business process automation as a fully managed service." },
  { key: "hero.checklist.1", value: "No infrastructure to build or maintain" },
  { key: "hero.checklist.2", value: "No internal automation team needed" },
  { key: "hero.checklist.3", value: "Fast ROI with predictable costs" },
  { key: "hero.checklist.4", value: "Most processes pay back within 6–12 months" },
  { key: "hero.cta", value: "Calculate Your ROI" },

  { key: "service.label", value: "Managed Intelligent Automation" },
  { key: "service.quote", value: "You Run <b>the Business.</b><br>We Run <b>the Automation.</b>" },
  { key: "service.intro", value: "Managed Automation delivers business process automation as a fully managed service." },
  { key: "service.bullet.1", value: "Instead of building an automation platform and internal team, organizations can simply automate their processes through our service." },
  { key: "service.bullet.2", value: "BCA designs, develops, and operates the automations end-to-end, removing the operational complexity from our clients." },
  { key: "service.bullet.3", value: "This enables organizations to achieve fast and measurable ROI, benefit from predictable service costs, and scale automation across the business." },

  { key: "pillars.title", value: "Why Organizations Choose Managed Automation" },
  { key: "pillars.1.title", value: "Lower Complexity" },
  { key: "pillars.1.description", value: "No platform to manage" },
  { key: "pillars.1.icon", value: "Layers" },
  { key: "pillars.2.title", value: "Lower Risk" },
  { key: "pillars.2.description", value: "Start small, No commitment" },
  { key: "pillars.2.icon", value: "ShieldCheck" },
  { key: "pillars.3.title", value: "Fast Time-to-Value" },
  { key: "pillars.3.description", value: "Live in weeks, not months" },
  { key: "pillars.3.icon", value: "Clock" },
  { key: "pillars.4.title", value: "Predictable Cost" },
  { key: "pillars.4.description", value: "Transparent, scalable pricing" },
  { key: "pillars.4.icon", value: "Calculator" },

  { key: "complexity.headline", value: "Find Your Process in Seconds" },
  { key: "complexity.subline", value: "From simple repetitive tasks to complex, end-to-end workflows" },
  { key: "complexity.small.name", value: "Small" },
  { key: "complexity.small.systems", value: "1 system \u00b7 simple, repetitive tasks" },
  { key: "complexity.small.bullet.1", value: "Data entry in business systems" },
  { key: "complexity.small.bullet.2", value: "Standard report generation" },
  { key: "complexity.small.bullet.3", value: "Email-based updates" },
  { key: "complexity.medium.name", value: "Medium" },
  { key: "complexity.medium.systems", value: "2 systems \u00b7 structured workflows" },
  { key: "complexity.medium.bullet.1", value: "Invoice processing from structured input" },
  { key: "complexity.medium.bullet.2", value: "Data transfer between systems" },
  { key: "complexity.medium.bullet.3", value: "Multi-source reporting" },
  { key: "complexity.large.name", value: "Large" },
  { key: "complexity.large.systems", value: "2\u20133 systems \u00b7 multi-step processes" },
  { key: "complexity.large.bullet.1", value: "Approval workflows with multiple steps" },
  { key: "complexity.large.bullet.2", value: "Customer or partner data validation" },
  { key: "complexity.large.bullet.3", value: "Document handling across systems" },
  { key: "complexity.complex.name", value: "Complex" },
  { key: "complexity.complex.systems", value: "3+ systems \u00b7 end-to-end automation" },
  { key: "complexity.complex.bullet.1", value: "End-to-end finance processes" },
  { key: "complexity.complex.bullet.2", value: "Cross-system operations" },
  { key: "complexity.complex.bullet.3", value: "Complex calculation and reconciliation" },

  { key: "calculator.title", value: "Estimate Your Automation ROI" },
  { key: "calculator.description", value: "Use this calculator to get a quick estimate of how much time and cost your organization could save by automating a specific business process. Simply select the complexity of the process, enter the monthly hours currently spent on it, and your average hourly cost — then see your projected annual savings, payback period, and ROI." },

  { key: "example.title", value: "Typical ROI From Automating a Single Process" },
  { key: "example.manual.title", value: "Manual process" },
  { key: "example.manual.hours", value: "~2 hours/day" },
  { key: "example.manual.rate", value: "\u20AC40/hour" },
  { key: "example.manual.cost", value: "\u20AC16,800 annual cost" },
  { key: "example.automation.title", value: "Automation" },
  { key: "example.automation.setup", value: "\u20AC10,000 setup" },
  { key: "example.automation.service", value: "\u20AC5,000 annual service" },
  { key: "example.impact.title", value: "Business impact" },
  { key: "example.impact.savings", value: "~\u20AC12,000 savings" },
  { key: "example.impact.payback", value: "~10-month payback" },
  { key: "example.impact.roi", value: "~100% ROI" },
  { key: "example.footer", value: "Small processes. Big impact." },

  { key: "pricing.title", value: "Automation Engagement Model" },
  { key: "pricing.starter.name", value: "Starter" },
  { key: "pricing.starter.description", value: "1 process" },
  { key: "pricing.starter.setup", value: "\u20AC10,000" },
  { key: "pricing.starter.annual", value: "\u20AC5,000" },
  { key: "pricing.growth.name", value: "Growth" },
  { key: "pricing.growth.description", value: "2\u201310 processes" },
  { key: "pricing.growth.setup", value: "\u20AC9,500" },
  { key: "pricing.growth.annual", value: "\u20AC4,500" },
  { key: "pricing.scale.name", value: "Scale" },
  { key: "pricing.scale.description", value: "10+ processes" },
  { key: "pricing.scale.setup", value: "\u20AC9,000" },
  { key: "pricing.scale.annual", value: "\u20AC4,000" },
  { key: "pricing.note", value: "* Setup fee depends on process complexity." },

  { key: "cta.headline", value: "Start With One Process" },
  { key: "cta.subheadline", value: "Validate ROI quickly and scale automation." },
  { key: "cta.button", value: "Request assessment" },
  { key: "cta.successMessage", value: "We'll be in touch shortly to schedule your assessment." },

  { key: "footer.tagline", value: "Experts In Technology, Partners In Business" },
  { key: "footer.subtitle", value: "Empowering Your Digital Journey since 2007" },
  { key: "footer.social.facebook", value: "https://facebook.com/bcasolutions" },
  { key: "footer.social.linkedin", value: "https://linkedin.com/company/bcasolutions" },
  { key: "footer.social.instagram", value: "https://instagram.com/bcasolutions" },
  { key: "footer.social.website", value: "https://bcasolutions.hu" },
  { key: "footer.copyright", value: "BCA Solutions. All rights reserved." },
  { key: "footer.privacy.text", value: "Privacy Policy" },
  { key: "footer.privacy.url", value: "#" },

  { key: "seo.title", value: "BCA Solutions — Managed Intelligent Automation" },
  { key: "seo.description", value: "Deliver business process automation as a fully managed service. No infrastructure, no internal team needed. Calculate your ROI today." },
  { key: "seo.ogTitle", value: "BCA Solutions — Managed Intelligent Automation" },
  { key: "seo.ogDescription", value: "We run the automation so you can run the business. Fast ROI, predictable costs, zero operational burden." },
  { key: "seo.ogImage", value: "" },
  { key: "seo.canonical", value: "" },
  { key: "seo.keywords", value: "managed automation, business process automation, RPA, ROI calculator, BCA Solutions" },

  { key: "privacy.content", value: "" },
];

export const calculatorConstants: { key: string; value: unknown }[] = [
  {
    key: "pricing",
    value: {
      S: { setup: 5000, service: 3000 },
      M: { setup: 10000, service: 5000 },
      L: { setup: 17500, service: 7000 },
    },
  },
  { key: "automationRatio", value: 0.9 },
  { key: "workingHoursPerMonth", value: 144 },
];
